sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

matrix:
  include:
    - php: 5.3
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=nightly
    # - php: 5.6
    #   env: WP_TRAVISCI=phpcs
  fast_finish: true

before_script:
  - composer install
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      npm install
    fi

script:
  - find . -path ./vendor -prune -o -type "f" -iname "*.php" | xargs -L "1" php -l
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then

      # Since phpunit 6 doesn't currently behave...
      phpunit_path="/tmp/phpunit-5.7"
      wget https://phar.phpunit.de/phpunit-5.7.phar -O $phpunit_path
      chmod +x $phpunit_path
      eval $phpunit_path --version

      eval $phpunit_path
      eval $phpunit_path -c multisite.xml
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      grunt phpcs
    fi
