name: Built Release

on:
  push:
    branches:
      - develop

jobs:
  built-release:
    uses: alleyinteractive/.github/.github/workflows/built-release.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    with:
      composer_install: false
      node: 20
