name: Deploy to WordPress.org
on:
  push:
    tags:
    - "*"
  workflow_dispatch:

jobs:
  push-built-release:
    name: Deploy plugin version to WP.org
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_TOKEN }}
    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: publish-to-apple-news
