name: Node Tests

on:
  push:
    branches:
      - develop
      - release/*
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
    branches:
      - develop
      - release/*

jobs:
  node-tests:
    if: github.event.pull_request.draft == false
    uses: alleyinteractive/.github/.github/workflows/node-tests.yml@main
    with:
      ci: true
      node: 16
      run-audit: false
      working-directory: ./
