name: PHP Coding Standards

on:
  push:
    branches:
      - develop
      - release/*
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
    branches:
      - develop
      - release/*

permissions:
  contents: read

jobs:
  phpcs:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6

      - name: Run PHPCS
        uses: alleyinteractive/action-test-php@v1
        with:
          php-version: '8.5'
          skip-wordpress-install: 'true'
          skip-services: 'true'
          skip-audit: 'true'
          test-command: composer run phpcs
