name: Testing Suite

on:
  push:
    branches:
      - develop
      - release/*
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
    branches:
      - develop
      - release/*

permissions:
  contents: read

jobs:
  phpcs:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6

      - name: Run PHPCS
        uses: alleyinteractive/action-test-php@v1
        with:
          php-version: '8.5'
          skip-wordpress-install: 'true'
          skip-services: 'true'
          skip-audit: 'true'
          test-command: composer run phpcs

  php-tests:
    continue-on-error: ${{ matrix.experimental == true }}
    strategy:
      matrix:
        multisite: [true, false]
        php: ['8.5', '8.4', '8.3', '8.2']
        wordpress: ["latest"]
        include:
          - php: '8.5'
            wordpress: 'latest'
            multisite: true
            experimental: true
          - php: '8.5'
            wordpress: 'latest'
            multisite: false
            experimental: true
          - php: '8.2'
            wordpress: '6.3'
            multisite: false
    if: github.event.pull_request.draft == false
    uses: alleyinteractive/.github/.github/workflows/php-tests.yml@main
    with:
      command: "phpunit"
      multisite: ${{ matrix.multisite }}
      php: ${{ matrix.php }}
      wordpress: ${{ matrix.wordpress }}
